# Generated by Django 2.0.5 on 2018-06-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180529_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Ogolne', 'Ogolne'), ('Z', 'Zwierzeta')], default='Z', max_length=50),
        ),
    ]
